# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 580de62367018c75806b2fad1c7a4c96658ec77b959eb0deb9b2266a9fec58e5734caae50d59a4206f7055a8634447698d94205695c7a061d4912a7dce9bddf8

test:
  secret_key_base: 918e972527d028d40742b715178e7dfddaebabc5722864d9f0ea216870bacc193638cb543f8750501e5d9267f047444346ffb146378057acdfeedb8a73287045

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
